//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accountant_View
    {
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string JobTitle { get; set; }
        public int AccountingtestID { get; set; }
        public int ApplicantID { get; set; }
        public string Accountingtest1 { get; set; }
        public string Accountingtest2 { get; set; }
        public string Accountingtest3_1 { get; set; }
        public string Accountingtest3_2 { get; set; }
        public string Accountingtest3_3 { get; set; }
        public string Accountingtest4 { get; set; }
        public string Accountingtest5 { get; set; }
        public string Accountingtest6 { get; set; }
        public string Accountingtest7 { get; set; }
        public string Accountingtest8 { get; set; }
        public string Accountingtest9 { get; set; }
        public string Accountingtest10 { get; set; }
        public string Solution1 { get; set; }
        public string Solution3_1 { get; set; }
        public string Solution3_2 { get; set; }
        public string Solution3_3 { get; set; }
        public string Solution4 { get; set; }
        public string Solution7 { get; set; }
        public string Solution8 { get; set; }
        public string Solution10 { get; set; }
        public string Accounttitle1 { get; set; }
        public string Accounttitle2 { get; set; }
        public string Accounttitle3 { get; set; }
        public string Accounttitle4 { get; set; }
        public string Accounttitle5 { get; set; }
        public string Accounttitle6 { get; set; }
        public string Accounttitle7 { get; set; }
        public string Accounttitle8 { get; set; }
        public string Accounttitle9 { get; set; }
        public string Accounttitle10 { get; set; }
        public string Accounttitle11 { get; set; }
        public string Accounttitle12 { get; set; }
        public string Accounttitle13 { get; set; }
        public string Debit1 { get; set; }
        public string Debit2 { get; set; }
        public string Debit3 { get; set; }
        public string Debit4 { get; set; }
        public string Debit5 { get; set; }
        public string Debit6 { get; set; }
        public string Debit7 { get; set; }
        public string Debit8 { get; set; }
        public string Debit9 { get; set; }
        public string Debit10 { get; set; }
        public string Debit11 { get; set; }
        public string Debit12 { get; set; }
        public string Debit13 { get; set; }
        public string Credit1 { get; set; }
        public string Credit2 { get; set; }
        public string Credit3 { get; set; }
        public string Credit4 { get; set; }
        public string Credit5 { get; set; }
        public string Credit6 { get; set; }
        public string Credit7 { get; set; }
        public string Credit8 { get; set; }
        public string Credit9 { get; set; }
        public string Credit10 { get; set; }
        public string Credit11 { get; set; }
        public string Credit12 { get; set; }
        public string Credit13 { get; set; }
        public string Accountingtestshort2 { get; set; }
        public string Taxbracket1 { get; set; }
        public string Taxbracket2 { get; set; }
        public string Taxbracket3 { get; set; }
        public string Rate1 { get; set; }
        public string Rate2 { get; set; }
        public string Rate3 { get; set; }
        public string Amount1 { get; set; }
        public string Amount2 { get; set; }
        public string Amount3 { get; set; }
        public string Totalincometax { get; set; }
        public string Booktitle1 { get; set; }
        public string Booktitle2 { get; set; }
        public string Booktitle3 { get; set; }
        public string Booktitle4 { get; set; }
        public string Bookdebit1 { get; set; }
        public string Bookdebit2 { get; set; }
        public string Bookdebit3 { get; set; }
        public string Bookdebit4 { get; set; }
        public string Bookcredit1 { get; set; }
        public string Bookcredit2 { get; set; }
        public string Bookcredit3 { get; set; }
        public string Bookcredit4 { get; set; }
        public string Balancebook { get; set; }
        public string Banktitle1 { get; set; }
        public string Banktitle2 { get; set; }
        public string Banktitle3 { get; set; }
        public string Banktitle4 { get; set; }
        public string Banktitle5 { get; set; }
        public string Banktitle6 { get; set; }
        public string Banktitle7 { get; set; }
        public string Bankdebit1 { get; set; }
        public string Bankdebit2 { get; set; }
        public string Bankdebit3 { get; set; }
        public string Bankdebit4 { get; set; }
        public string Bankdebit5 { get; set; }
        public string Bankdebit6 { get; set; }
        public string Bankdebit7 { get; set; }
        public string Bankcredit1 { get; set; }
        public string Bankcredit2 { get; set; }
        public string Bankcredit3 { get; set; }
        public string Bankcredit4 { get; set; }
        public string Bankcredit5 { get; set; }
        public string Bankcredit6 { get; set; }
        public string Bankcredit7 { get; set; }
        public string Balancebank { get; set; }
        public string Asset1 { get; set; }
        public string Asset2 { get; set; }
        public string Asset3 { get; set; }
        public string Asset4 { get; set; }
        public string Asset5 { get; set; }
        public string Asset6 { get; set; }
        public string Asset7 { get; set; }
        public string Debitasset1 { get; set; }
        public string Debitasset2 { get; set; }
        public string Debitasset3 { get; set; }
        public string Debitasset4 { get; set; }
        public string Debitasset5 { get; set; }
        public string Debitasset6 { get; set; }
        public string Debitasset7 { get; set; }
        public string Creditasset1 { get; set; }
        public string Creditasset2 { get; set; }
        public string Creditasset3 { get; set; }
        public string Creditasset4 { get; set; }
        public string Creditasset5 { get; set; }
        public string Creditasset6 { get; set; }
        public string Creditasset7 { get; set; }
        public string Totalasset { get; set; }
        public string Equity1 { get; set; }
        public string Equity2 { get; set; }
        public string Equity3 { get; set; }
        public string Equity4 { get; set; }
        public string Equity5 { get; set; }
        public string Equity6 { get; set; }
        public string Equity7 { get; set; }
        public string Equity8 { get; set; }
        public string Debitequity1 { get; set; }
        public string Debitequity2 { get; set; }
        public string Debitequity3 { get; set; }
        public string Debitequity4 { get; set; }
        public string Debitequity5 { get; set; }
        public string Debitequity6 { get; set; }
        public string Debitequity7 { get; set; }
        public string Debitequity8 { get; set; }
        public string Creditequity1 { get; set; }
        public string Creditequity2 { get; set; }
        public string Creditequity3 { get; set; }
        public string Creditequity4 { get; set; }
        public string Creditequity5 { get; set; }
        public string Creditequity6 { get; set; }
        public string Creditequity7 { get; set; }
        public string Creditequity8 { get; set; }
        public string Totalequity { get; set; }
    }
}
