//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpHistory
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DatePromoted { get; set; }
        public string EmploymentStatus { get; set; }
        public string Department { get; set; }
        public string JobTitle { get; set; }
        public string OfficeLocation { get; set; }
        public Nullable<decimal> GrossPay { get; set; }
        public Nullable<decimal> Allowance { get; set; }
    }
}
