//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Essay_View
    {
        public int EssayID { get; set; }
        public int ApplicantID { get; set; }
        public string Essay1 { get; set; }
        public string Essay2 { get; set; }
        public string Essay3 { get; set; }
        public string Essay4 { get; set; }
        public string Essay5 { get; set; }
        public string Essay6 { get; set; }
        public string Essay7 { get; set; }
        public string Essay8 { get; set; }
        public string Essay9 { get; set; }
        public string Essay10 { get; set; }
        public string Essay11 { get; set; }
        public string Essay12 { get; set; }
        public string Essay13 { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string JobTitle { get; set; }
    }
}
