//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_IQtest
    {
        public int IQtestID { get; set; }
        public int ApplicantID { get; set; }
        public string IQtest1 { get; set; }
        public string IQtest2 { get; set; }
        public string IQtest3 { get; set; }
        public string IQtest4 { get; set; }
        public string IQtest5 { get; set; }
        public string IQtest6 { get; set; }
        public string IQtest7 { get; set; }
        public string IQtest8 { get; set; }
        public string IQtest9 { get; set; }
        public string IQtest10 { get; set; }
        public string IQtest11 { get; set; }
        public string IQtest12 { get; set; }
        public string IQtest13 { get; set; }
        public string IQtest14 { get; set; }
        public string IQtest15 { get; set; }
        public string IQtest16 { get; set; }
        public string IQtest17 { get; set; }
        public string IQtest18 { get; set; }
        public string IQtest19 { get; set; }
        public string IQtest20 { get; set; }
        public string IQtest21 { get; set; }
        public string IQtest22 { get; set; }
        public string IQtest23 { get; set; }
        public string IQtest24 { get; set; }
        public string IQtest25 { get; set; }
        public string IQtest26 { get; set; }
        public string IQtest27 { get; set; }
        public string IQtest28 { get; set; }
        public string IQtest29 { get; set; }
        public string IQtest30 { get; set; }
        public string score { get; set; }
    }
}
