//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveForm
    {
        public int LeaveID { get; set; }
        public string Description { get; set; }
        public string TypeOfRequest { get; set; }
        public string Approver { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public string LeaveStatus { get; set; }
        public Nullable<System.DateTime> DateRequest { get; set; }
    }
}
