//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masterlist
    {
        public Nullable<int> EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Department { get; set; }
        public string JobTitle { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string MaritalStatus { get; set; }
        public string Gender { get; set; }
        public string ContactNumber { get; set; }
        public string Street_Address1 { get; set; }
        public string Street_Address2 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string ZipCode { get; set; }
        public string PersonalEmail { get; set; }
        public string CompanyEmail { get; set; }
        public Nullable<decimal> GrossPay { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public Nullable<int> AvailableLeave { get; set; }
        public Nullable<int> UsedLeave { get; set; }
        public string SSS { get; set; }
        public string Pagibig { get; set; }
        public string PhilHealth { get; set; }
        public string TinNumber { get; set; }
        public Nullable<int> SSS_loan { get; set; }
        public Nullable<int> Pagibig_loan { get; set; }
        public Nullable<System.DateTime> DateHired { get; set; }
        public Nullable<System.DateTime> DatePromoted { get; set; }
        public Nullable<System.DateTime> DateResigned { get; set; }
        public string EmploymentStatus { get; set; }
        public Nullable<System.DateTime> Applicant_AppliedDate { get; set; }
        public Nullable<System.DateTime> Applicant_ExamDate { get; set; }
        public string Applicant_InitialInterviewDate { get; set; }
        public Nullable<System.DateTime> Applicant_FinalInterviewDate { get; set; }
        public string Applicant_Resume { get; set; }
        public Nullable<int> Applicant_InitialInterview { get; set; }
        public Nullable<int> Applicant_FinalInterview { get; set; }
        public string Applicant_InitialInterviewer { get; set; }
        public string Applicant_FinalInterviewer { get; set; }
        public string ProfilePicture { get; set; }
        public Nullable<int> Applicant_ExamNo { get; set; }
        public Nullable<int> Applicant_TookExam { get; set; }
        public string School_Primary { get; set; }
        public string School_Secondary { get; set; }
        public string School_Tertiary { get; set; }
        public Nullable<int> School_TertiaryYearGraduated { get; set; }
        public string School_Degree { get; set; }
        public int MasterlistID { get; set; }
        public string Country { get; set; }
        public string Nationality { get; set; }
    }
}
