//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryCheckInOut
    {
        public int Expr1 { get; set; }
        public string Badgenumber { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> checkdate { get; set; }
        public Nullable<System.TimeSpan> checktime { get; set; }
        public string CHECKTYPE { get; set; }
    }
}
